"""inition migrateion

Revision ID: 080967aac4a1
Revises: a04c589fe9e2
Create Date: 2018-08-12 12:12:04.669962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080967aac4a1'
down_revision = 'a04c589fe9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('illus', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testBlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('illus', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testBlog')
    op.drop_table('portfolios')
    op.drop_table('blogs')
    # ### end Alembic commands ###
